version: "3.8"
services:
  app:
    build: .
    ports:
      - 3000:4000
    env_file: .env
    depends_on:
      - db
  db:
    image: 'postgres'
    environment:
      POSTGRES_USER: Ilya.Istomin
      POSTGRES_PASSWORD: IlyaIlya
      POSTGRES_DB: studentsLabDB
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: